### PR TITLE
ci: aggregate message from testing & stages

### PR DESCRIPTION
**Pull request by Borda**
## Before submitting

- [x] Was this discussed/approved via a GitHub issue? (no need for typos and docs improvements)
- [ ] Did you create/update your **configuration file**?
- [ ] Did you **set `runtimes` in config** for GitHub action integration?
- [ ] Did you **add your config to CI** in Azure pipeline (only projects with 100+ GitHub stars)?
- [ ] Are all integration **tests passing**?

## What does this PR do? \[optional\]

collecting results and reporting all at once not per failed job so as to limit spam
image

this also allow to set required check for `watcher` for PRs

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
inspirations:
- https://stackoverflow.com/questions/70287603/github-actions-dynamic-outputs-for-job-with-strategy-matrix

**Comment by Borda** [comment]
Slack sample with default/template 
image

**Comment by Borda** [comment]
fyi, the required check will be updated accordingly :chipmunk:

**Review by akihironitta — APPROVED** [review]
LGTM! (nit: messanger -> messenger)

**Pull request merged**
